name: lipl_display
description: Showing Lyrics on gatt peripheral
publish_to: 'none' 
version: 1.0.4

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.75.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  ffigen: ">=8.0.0 <9.0.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.4.2

platforms:
  linux:

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
