name: lipl_display
description: Lipl display for showing Lyrics sent to gatt peripheral
publish_to: 'none' 
version: 1.0.4

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.38.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

platforms:
  linux:

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
