name: lipl_display
description: Showing Lyrics on gatt peripheral
publish_to: 'none' 
version: 1.0.4

environment:
  sdk: "^3.3.1"
  flutter: ">=3.19.3 <4.0.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  test: any

platforms:
  linux:

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
