#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.1.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_gatt_listen_impl(
    port_: MessagePort,
    part: impl Wire2Api<String> + UnwindSafe,
    status: impl Wire2Api<String> + UnwindSafe,
    dark: impl Wire2Api<bool> + UnwindSafe,
    font_size: impl Wire2Api<f32> + UnwindSafe,
    font_size_increment: impl Wire2Api<f32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "gatt_listen",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_part = part.wire2api();
            let api_status = status.wire2api();
            let api_dark = dark.wire2api();
            let api_font_size = font_size.wire2api();
            let api_font_size_increment = font_size_increment.wire2api();
            move |task_callback| {
                gatt_listen(
                    task_callback.stream_sink(),
                    api_part,
                    api_status,
                    api_dark,
                    api_font_size,
                    api_font_size_increment,
                )
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}
impl Wire2Api<f32> for f32 {
    fn wire2api(self) -> f32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for LiplDisplay {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.part.into_dart(),
            self.status.into_dart(),
            self.dark.into_dart(),
            self.font_size.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LiplDisplay {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
